### ISSUE TITLE
Mihon: Add instructions to install the extension repository

### ISSUE THREAD

**Issue by laurentlbm** [Kareadita/Wiki-Nextra#10]
The instructions on the [wiki](https://wiki.kavitareader.com/guides/3rdparty/tachi-like) say to search and install the Kavita extension from inside the app, but that information is incomplete. Ever since Mihon was forked from Tachiyomi, the app doesn't include any extension repository anymore. Therefore, the Kavita extension cannot be found. The wiki should include an extra step to explain how to add [the Kavita extension repository](https://github.com/Kareadita/tachiyomi-extensions) to Mihon.

**Comment by majora2007** [comment]
Would you be open to submitting a PR?

**Comment by laurentlbm** [comment]
If I have time, I will, but can't promise anything.
